AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Image:
    Type: String
Resources:
  Log:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/ecs/http'
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 256
      ContainerDefinitions:
      - Name: 'http'
        Environment:
        - Name: 'JAVA_OPTS'
          Value:
            Fn::Join:
            - ' '
            - - '-Djava.rmi.server.hostname=127.0.0.1'
              - '-Dcom.sun.management.jmxremote=true'
              - '-Dcom.sun.management.jmxremote.port=9010'
              - '-Dcom.sun.management.jmxremote.rmi.port=9010'
              - '-Dcom.sun.management.jmxremote.ssl=false'
              - '-Dcom.sun.management.jmxremote.authenticate=false'
              - '-Dcom.sun.management.jmxremote.local.only=false'
        Image: !Ref 'Image'
        LogConfiguration:
          LogDriver: 'awslogs'
          Options:
            awslogs-group: !Ref Log
            awslogs-region: !Ref AWS::Region
        MemoryReservation: 512
        PortMappings:
        - ContainerPort: 8080
        - ContainerPort: 9010
      Memory: 512
      Family: http
      RequiresCompatibilities: EC2
  Service:
    Type: AWS::ECS::Service
    Properties:
      Role:
        Fn::ImportValue: 'ecsservice-role'
      TaskDefinition: !Ref 'Task'
      DesiredCount: 0
      Cluster: 'http-cluster'
